#task_3. Конвертация валюс (доллар, курс, вывод в рублях)
print("Задание 3")
dol = float(input("Значение в долларах: "))
conver = float(input("Текущий курс: "))
print("Значение в рублях: ", round(dol*conver, 2))